export { Hero } from "./Hero";
export { About } from "./About";
export { Services } from "./Services";
export { Assignments } from "./Assignments";
export { Experience } from "./Experience";
export { Process } from "./Process";
export { Clients } from "./Clients";
export { Contact } from "./Contact";
export { Footer } from "./Footer";
